{
  "Header": {
    "Original": "CVE-2023-0645 (An out of bounds read exists in libjxl. An attacker using a specifical ...)",
    "ID": "CVE-2023-0645",
    "Description": "(An out of bounds read exists in libjxl. An attacker using a specifical ...)"
  },
  "Annotations": [
    {
      "Original": "{DSA-5958-1}",
      "Type": "xref",
      "Bugs": [
        "DSA-5958-1"
      ]
    },
    {
      "Original": "[experimental] - jpeg-xl 0.8.2-1",
      "Type": "package",
      "Release": "experimental",
      "Package": "jpeg-xl",
      "Kind": "fixed",
      "Version": "0.8.2-1"
    },
    {
      "Original": "- jpeg-xl 0.8.2-4 (bug #1034722)",
      "Type": "package",
      "Package": "jpeg-xl",
      "Kind": "fixed",
      "Version": "0.8.2-4",
      "BugNo": 1034722
    },
    {
      "Original": "NOTE: https://github.com/libjxl/libjxl/commit/a7c8428b61299f3b055cbbdbba3fbcd8cb38d084",
      "Type": "NOTE",
      "Description": "https://github.com/libjxl/libjxl/commit/a7c8428b61299f3b055cbbdbba3fbcd8cb38d084"
    },
    {
      "Original": "NOTE: https://github.com/libjxl/libjxl/issues/2100",
      "Type": "NOTE",
      "Description": "https://github.com/libjxl/libjxl/issues/2100"
    },
    {
      "Original": "NOTE: https://github.com/libjxl/libjxl/pull/2101",
      "Type": "NOTE",
      "Description": "https://github.com/libjxl/libjxl/pull/2101"
    }
  ]
}