{
  "Header": {
    "Original": "CVE-2024-31584 (Pytorch before v2.2.0 has an Out-of-bounds Read vulnerability via the  ...)",
    "ID": "CVE-2024-31584",
    "Description": "(Pytorch before v2.2.0 has an Out-of-bounds Read vulnerability via the  ...)"
  },
  "Annotations": [
    {
      "Original": "- pytorch 2.4.1-1 (bug #1070379)",
      "Type": "package",
      "Package": "pytorch",
      "Kind": "fixed",
      "Version": "2.4.1-1",
      "BugNo": 1070379
    },
    {
      "Original": "[bookworm] - pytorch \u003cignored\u003e (Minor issue)",
      "Type": "package",
      "Release": "bookworm",
      "Package": "pytorch",
      "Kind": "ignored",
      "Description": "Minor issue"
    },
    {
      "Original": "[bullseye] - pytorch \u003cnot-affected\u003e (Vulnerable code introduced later)",
      "Type": "package",
      "Release": "bullseye",
      "Package": "pytorch",
      "Kind": "not-affected",
      "Description": "Vulnerable code introduced later"
    },
    {
      "Original": "NOTE: https://github.com/pytorch/pytorch/commit/7c35874ad664e74c8e4252d67521f3986eadb0e6",
      "Type": "NOTE",
      "Description": "https://github.com/pytorch/pytorch/commit/7c35874ad664e74c8e4252d67521f3986eadb0e6"
    }
  ]
}