{
  "Header": {
    "Original": "CVE-2024-4032 (The \\u201cipaddress\\u201d module contained incorrect information about ...)",
    "ID": "CVE-2024-4032",
    "Description": "(The \\u201cipaddress\\u201d module contained incorrect information about ...)"
  },
  "Annotations": [
    {
      "Original": "{DSA-5759-1 DLA-3980-1}",
      "Type": "xref",
      "Bugs": [
        "DSA-5759-1",
        "DLA-3980-1"
      ]
    },
    {
      "Original": "- python3.13 \u003cnot-affected\u003e (Fixed before initial upload to Debian unstable)",
      "Type": "package",
      "Package": "python3.13",
      "Kind": "not-affected",
      "Description": "Fixed before initial upload to Debian unstable"
    },
    {
      "Original": "- python3.12 3.12.4-1",
      "Type": "package",
      "Package": "python3.12",
      "Kind": "fixed",
      "Version": "3.12.4-1"
    },
    {
      "Original": "- python3.11 \u003cremoved\u003e",
      "Type": "package",
      "Package": "python3.11",
      "Kind": "removed"
    },
    {
      "Original": "- python3.9 \u003cremoved\u003e",
      "Type": "package",
      "Package": "python3.9",
      "Kind": "removed"
    },
    {
      "Original": "- python3.7 \u003cremoved\u003e",
      "Type": "package",
      "Package": "python3.7",
      "Kind": "removed"
    },
    {
      "Original": "- python2.7 \u003cnot-affected\u003e (ipaddress module added in 3.3)",
      "Type": "package",
      "Package": "python2.7",
      "Kind": "not-affected",
      "Description": "ipaddress module added in 3.3"
    },
    {
      "Original": "- pypy3 7.3.18+dfsg-1",
      "Type": "package",
      "Package": "pypy3",
      "Kind": "fixed",
      "Version": "7.3.18+dfsg-1"
    },
    {
      "Original": "[bullseye] - pypy3 \u003cpostponed\u003e (Minor issue)",
      "Type": "package",
      "Release": "bullseye",
      "Package": "pypy3",
      "Kind": "postponed",
      "Description": "Minor issue"
    },
    {
      "Original": "NOTE: https://github.com/advisories/GHSA-mh6q-v4mp-2cc7",
      "Type": "NOTE",
      "Description": "https://github.com/advisories/GHSA-mh6q-v4mp-2cc7"
    },
    {
      "Original": "NOTE: https://github.com/python/cpython/issues/113171",
      "Type": "NOTE",
      "Description": "https://github.com/python/cpython/issues/113171"
    },
    {
      "Original": "NOTE: https://github.com/python/cpython/pull/113179",
      "Type": "NOTE",
      "Description": "https://github.com/python/cpython/pull/113179"
    },
    {
      "Original": "NOTE: https://github.com/python/cpython/commit/ba431579efdcbaed7a96f2ac4ea0775879a332fb (v3.11.10)",
      "Type": "NOTE",
      "Description": "https://github.com/python/cpython/commit/ba431579efdcbaed7a96f2ac4ea0775879a332fb (v3.11.10)"
    },
    {
      "Original": "NOTE: https://github.com/python/cpython/commit/22adf29da8d99933ffed8647d3e0726edd16f7f8 (v3.9.20)",
      "Type": "NOTE",
      "Description": "https://github.com/python/cpython/commit/22adf29da8d99933ffed8647d3e0726edd16f7f8 (v3.9.20)"
    }
  ]
}