{
  "Header": {
    "Original": "CVE-2025-32910 (A flaw was found in libsoup, where soup_auth_digest_authenticate() is  ...)",
    "ID": "CVE-2025-32910",
    "Description": "(A flaw was found in libsoup, where soup_auth_digest_authenticate() is  ...)"
  },
  "Annotations": [
    {
      "Original": "{DLA-4140-1}",
      "Type": "xref",
      "Bugs": [
        "DLA-4140-1"
      ]
    },
    {
      "Original": "- libsoup3 3.6.4-1",
      "Type": "package",
      "Package": "libsoup3",
      "Kind": "fixed",
      "Version": "3.6.4-1"
    },
    {
      "Original": "[bookworm] - libsoup3 \u003cno-dsa\u003e (Minor issue)",
      "Type": "package",
      "Release": "bookworm",
      "Package": "libsoup3",
      "Kind": "no-dsa",
      "Description": "Minor issue"
    },
    {
      "Original": "- libsoup2.4 2.74.3-10.1 (bug #1103516)",
      "Type": "package",
      "Package": "libsoup2.4",
      "Kind": "fixed",
      "Version": "2.74.3-10.1",
      "BugNo": 1103516
    },
    {
      "Original": "[bookworm] - libsoup2.4 \u003cno-dsa\u003e (Minor issue)",
      "Type": "package",
      "Release": "bookworm",
      "Package": "libsoup2.4",
      "Kind": "no-dsa",
      "Description": "Minor issue"
    },
    {
      "Original": "NOTE: https://gitlab.gnome.org/GNOME/libsoup/-/issues/432",
      "Type": "NOTE",
      "Description": "https://gitlab.gnome.org/GNOME/libsoup/-/issues/432"
    },
    {
      "Original": "NOTE: https://gitlab.gnome.org/GNOME/libsoup/-/merge_requests/417",
      "Type": "NOTE",
      "Description": "https://gitlab.gnome.org/GNOME/libsoup/-/merge_requests/417"
    },
    {
      "Original": "NOTE: Fixed by: https://gitlab.gnome.org/GNOME/libsoup/-/commit/ea16eeacb052e423eb5c3b0b705e5eab34b13832 (3.6.2)",
      "Type": "NOTE",
      "Description": "Fixed by: https://gitlab.gnome.org/GNOME/libsoup/-/commit/ea16eeacb052e423eb5c3b0b705e5eab34b13832 (3.6.2)"
    }
  ]
}