{
  "Header": {
    "Original": "CVE-2025-4516 (There is an issue in CPython when using `bytes.decode(\"unicode_escape\" ...)",
    "ID": "CVE-2025-4516",
    "Description": "(There is an issue in CPython when using `bytes.decode(\"unicode_escape\" ...)"
  },
  "Annotations": [
    {
      "Original": "- python3.13 3.13.3-4",
      "Type": "package",
      "Package": "python3.13",
      "Kind": "fixed",
      "Version": "3.13.3-4"
    },
    {
      "Original": "- python3.12 \u003cunfixed\u003e",
      "Type": "package",
      "Package": "python3.12",
      "Kind": "unfixed"
    },
    {
      "Original": "- python3.11 \u003cremoved\u003e",
      "Type": "package",
      "Package": "python3.11",
      "Kind": "removed"
    },
    {
      "Original": "[bookworm] - python3.11 \u003cno-dsa\u003e (Minor issue)",
      "Type": "package",
      "Release": "bookworm",
      "Package": "python3.11",
      "Kind": "no-dsa",
      "Description": "Minor issue"
    },
    {
      "Original": "- python3.9 \u003cremoved\u003e",
      "Type": "package",
      "Package": "python3.9",
      "Kind": "removed"
    },
    {
      "Original": "[bullseye] - python3.9 \u003cpostponed\u003e (Minor issue, likely DoS-only, fix along with next update)",
      "Type": "package",
      "Release": "bullseye",
      "Package": "python3.9",
      "Kind": "postponed",
      "Description": "Minor issue, likely DoS-only, fix along with next update"
    },
    {
      "Original": "- pypy3 \u003cnot-affected\u003e (Vulnerable code not present; memory error in C code implementation)",
      "Type": "package",
      "Package": "pypy3",
      "Kind": "not-affected",
      "Description": "Vulnerable code not present; memory error in C code implementation"
    },
    {
      "Original": "NOTE: https://mail.python.org/archives/list/security-announce@python.org/thread/L75IPBBTSCYEF56I2M4KIW353BB3AY74/",
      "Type": "NOTE",
      "Description": "https://mail.python.org/archives/list/security-announce@python.org/thread/L75IPBBTSCYEF56I2M4KIW353BB3AY74/"
    },
    {
      "Original": "NOTE: PoC: https://www.openwall.com/lists/oss-security/2025/05/19/1",
      "Type": "NOTE",
      "Description": "PoC: https://www.openwall.com/lists/oss-security/2025/05/19/1"
    },
    {
      "Original": "NOTE: https://github.com/python/cpython/issues/133767",
      "Type": "NOTE",
      "Description": "https://github.com/python/cpython/issues/133767"
    },
    {
      "Original": "NOTE: https://github.com/python/cpython/pull/129648",
      "Type": "NOTE",
      "Description": "https://github.com/python/cpython/pull/129648"
    },
    {
      "Original": "NOTE: https://github.com/python/cpython/commit/9f69a58623bd01349a18ba0c7a9cb1dad6a51e8e (main)",
      "Type": "NOTE",
      "Description": "https://github.com/python/cpython/commit/9f69a58623bd01349a18ba0c7a9cb1dad6a51e8e (main)"
    },
    {
      "Original": "NOTE: https://github.com/python/cpython/commit/69b4387f78f413e8c47572a85b3478c47eba8142 (v3.14.0b2)",
      "Type": "NOTE",
      "Description": "https://github.com/python/cpython/commit/69b4387f78f413e8c47572a85b3478c47eba8142 (v3.14.0b2)"
    },
    {
      "Original": "NOTE: https://github.com/python/cpython/commit/6279eb8c076d89d3739a6edb393e43c7929b429d (v3.13.4)",
      "Type": "NOTE",
      "Description": "https://github.com/python/cpython/commit/6279eb8c076d89d3739a6edb393e43c7929b429d (v3.13.4)"
    }
  ]
}