{
  "Header": {
    "Original": "CVE-2025-4476 (A denial-of-service vulnerability has been identified in the libsoup H ...)",
    "ID": "CVE-2025-4476",
    "Description": "(A denial-of-service vulnerability has been identified in the libsoup H ...)"
  },
  "Annotations": [
    {
      "Original": "- libsoup3 3.6.5-2 (bug #1105887)",
      "Type": "package",
      "Package": "libsoup3",
      "Kind": "fixed",
      "Version": "3.6.5-2",
      "BugNo": 1105887
    },
    {
      "Original": "[bookworm] - libsoup3 \u003cno-dsa\u003e (Minor issue)",
      "Type": "package",
      "Release": "bookworm",
      "Package": "libsoup3",
      "Kind": "no-dsa",
      "Description": "Minor issue"
    },
    {
      "Original": "- libsoup2.4 \u003cunfixed\u003e (bug #1107757)",
      "Type": "package",
      "Package": "libsoup2.4",
      "Kind": "unfixed",
      "BugNo": 1107757
    },
    {
      "Original": "[bookworm] - libsoup2.4 \u003cno-dsa\u003e (Minor issue)",
      "Type": "package",
      "Release": "bookworm",
      "Package": "libsoup2.4",
      "Kind": "no-dsa",
      "Description": "Minor issue"
    },
    {
      "Original": "NOTE: https://gitlab.gnome.org/GNOME/libsoup/-/issues/440",
      "Type": "NOTE",
      "Description": "https://gitlab.gnome.org/GNOME/libsoup/-/issues/440"
    },
    {
      "Original": "NOTE: https://gitlab.gnome.org/GNOME/libsoup/-/merge_requests/457",
      "Type": "NOTE",
      "Description": "https://gitlab.gnome.org/GNOME/libsoup/-/merge_requests/457"
    },
    {
      "Original": "NOTE: Fixed by: https://gitlab.gnome.org/GNOME/libsoup/-/commit/e64c221f9c7d09b48b610c5626b3b8c400f0907c",
      "Type": "NOTE",
      "Description": "Fixed by: https://gitlab.gnome.org/GNOME/libsoup/-/commit/e64c221f9c7d09b48b610c5626b3b8c400f0907c"
    },
    {
      "Original": "NOTE: https://bugzilla.redhat.com/show_bug.cgi?id=2366513",
      "Type": "NOTE",
      "Description": "https://bugzilla.redhat.com/show_bug.cgi?id=2366513"
    }
  ]
}